version: "3"
services:
  pruntime:
    image: phalanetwork/phala-pruntime
    container_name: phala-pruntime
    hostname: pruntime
    restart: always
    ports:
     - "8000:8000"
    devices:
       #- /dev/sgx/enclave
       #- /dev/sgx/provision
       - /dev/isgx
    environment:
     - EXTRA_OPTS=--cores=4
     - ROCKET_ADDRESS=0.0.0.0
    volumes:
     - /var/khala-pruntime-data:/root/data
